CREATE TABLE `containers` (
	`id` varchar(36) NOT NULL,
	`customer` varchar(191) NOT NULL,
	`type_survey` enum('In-serv','ONH','OFH','Sale') NOT NULL,
	`status` enum('Mty','Full') NOT NULL,
	`condition` enum('DMG','AVL','AR') NOT NULL,
	`cleanliness` enum('dty','ctm') NOT NULL,
	`survey_location` varchar(255) NOT NULL,
	`date_survey` datetime NOT NULL,
	`container_number` varchar(32) NOT NULL,
	`size` int NOT NULL,
	`date_manufactured` datetime NOT NULL,
	`type` varchar(64) NOT NULL,
	`csc` varchar(64) NOT NULL,
	`mgm` varchar(64) NOT NULL,
	`acep` varchar(64) NOT NULL,
	`payload` int NOT NULL,
	`tct` varchar(64) NOT NULL,
	`tare` int NOT NULL,
	`cu_cap` int NOT NULL,
	`surveyor_id` varchar(36),
	`note` varchar(2000),
	`third_scty_sys` varchar(191),
	`created_at` datetime NOT NULL,
	`updated_at` datetime NOT NULL,
	`deleted_at` datetime,
	CONSTRAINT `containers_id` PRIMARY KEY(`id`),
	CONSTRAINT `containers_container_number_unique` UNIQUE(`container_number`)
);
--> statement-breakpoint
CREATE TABLE `document_containers` (
	`id` varchar(36) NOT NULL,
	`container_id` varchar(36) NOT NULL,
	`side` enum('rear','front','left_side','right_side','roof','floor','understructure') NOT NULL,
	`section_h` varchar(1) NOT NULL,
	`section_v` varchar(1) NOT NULL,
	`combined_section` varchar(16) NOT NULL,
	`file_path` varchar(500) NOT NULL,
	`status` enum('Pending','Processing','Approved','Rejected') NOT NULL DEFAULT 'Pending',
	`uploaded_by_id` varchar(36) NOT NULL,
	`reviewed_by_id` varchar(36),
	`reviewed_at` datetime,
	`created_at` datetime NOT NULL,
	`updated_at` datetime NOT NULL,
	CONSTRAINT `document_containers_id` PRIMARY KEY(`id`)
);
